import Head from "next/head";
import Script from "next/script";
import AppTitle from "../components/AppTitle";
import CreateTODO from "../components/CreateTODO";
import FilterBar from "../components/FilterBar";
import TodoItem from "../components/TodoItem";
import "../styles/Home.module.css";
const list = ["todo 1", "todo 2", "todo 3"];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <body>
        <div className='container m-5 p-2 rounded mx-auto bg-light shadow'>
          {/* <!-- App title section --> */}
          <AppTitle />
          {/* <!-- Create todo section --> */}
          <CreateTODO />
          <div className='p-2 mx-4 border-black-25 border-bottom'></div>

          {/* <!-- View options section --> */}
          <FilterBar />
          {/* <!-- Todo list section --> */}
          <div className='row mx-1 px-5 pb-3 w-80'>
            <div className='col mx-auto'>
              {/* <!-- Todo Item 2 --> */}
              <ol>
                {list.map((t, i) => (
                  <li key={i}>
                    <TodoItem title={t} />
                  </li>
                ))}
              </ol>
            </div>
          </div>
        </div>
        <Script
          src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js'
          integrity='sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM'
          crossOrigin='anonymous'
        />
      </body>
    </div>
  );
}
